apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api
        image: usman212/inventory-api:v3
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=InventoryDb;User Id=sa;Password=Your_password123;"