apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
  namespace: inventory-app
spec:
  ingressClassName: nginx
  rules:
  - host: inventory.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inventory-api-service
            port:
              number: 80