apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: inventory-app
type: Opaque
stringData:
  SA_PASSWORD: "Your_password123"
  ConnectionString: "Server=sqlserver;Database=InventoryDb;User Id=sa;Password=Your_password123;"
